### ISSUE TITLE
0.11.5 on macos Big Sur 11.6

### ISSUE THREAD

**Issue by dem10com** [chaiNNer-org/chaiNNer#861]
In this version, the installation went smoothly and I downloaded the ncnn packages. but this time the model I am using on windows and I am sure it works (4x-UltraSharp-opt-fp16.bin ) gives a black screen. Anyone have experience with this before?

![Screen Shot 2022-08-29 at 12 24 43](https://user-images.githubusercontent.com/111634201/187170318-69ad5b72-32cc-4bd0-a5ef-c9864506a180.png)

**Comment by dem10com** [comment]
By the way, the reason for using ncnn is that the others are not using the gpu. pytorch is using only the cpu. 

thank you

**Comment by joeyballentine** [comment]
It seems like ncnn on macos is still broken unfortunately. It has something to do with vulkan, and I'm not sure what I can do to fix it. But I'll try

**Comment by dem10com** [comment]
> It seems like ncnn on macos is still broken unfortunately. It has something to do with vulkan, and I'm not sure what I can do to fix it. But I'll try

thanks a lot Joey

**Comment by joeyballentine** [comment]
Onnx does not have an arm64 (m1) version, therefore it is unable to be installed.

**Comment by joeyballentine** [comment]
Also this is the first I've heard of the ncnn m1 version I just released working. I was last told it produced black outputs as well. So this is good news I guess :)

**Comment by dem10com** [comment]
oh, Now I noticed that if it is more than 512x512 image size it gives a black screen.

**Comment by joeyballentine** [comment]
Thats probably due to the auto tiling then. If you set a target tile size of 512 does it always work?

**Comment by joeyballentine** [comment]
Hey @dem10com, I think I fixed this issue with 0.11.6 and the ncnn update that came with it. Could you give that a try?

**Comment by dem10com** [comment]
i try, install and update ncnn (2022.8.29). But i am getting this error.

An error occurred in a NCNN Upscale Image node:

An unexpected error occurred during NCNN processing.

Input values (partial):
• Image: RGB image 2048x2048
• Tile Size Target: 0
![Screen Shot 2022-08-30 at 13 15 34](https://user-images.githubusercontent.com/111634201/187411903-90381867-3597-4acb-9999-c100086b17b7.png)


I change the tile size target but nothing change.


> Hey @dem10com, I think I fixed this issue with 0.11.6 and the ncnn update that came with it. Could you give that a try?

**Comment by joeyballentine** [comment]
Can you set the target tile size to 0 and try again?

**Comment by joeyballentine** [comment]
I believe that error means you ran out of vram

**Comment by dem10com** [comment]
I tried with "0" at first and it didn't work. and try again nothing change

![Screen Shot 2022-08-30 at 13 57 51](https://user-images.githubusercontent.com/111634201/187419844-a4400ca0-e185-4eb0-9e55-dd2c6dd50f07.png)

**Comment by joeyballentine** [comment]
Oh that's weird. Well in that case could you try a lower v tile size target like 512

**Comment by dem10com** [comment]
here is the results;
 
![Screen Shot 2022-08-30 at 14 24 20](https://user-images.githubusercontent.com/111634201/187425250-e2f84364-0123-4d31-a30b-ed1020581fb8.png)

but if i exit the program and start it again. It works for a 512x512 image. same way when i restart i get same error on 2048x2048 or 1024x1024 master file. most likely vram error as you said

![Screen Shot 2022-08-30 at 14 26 19](https://user-images.githubusercontent.com/111634201/187425570-a3cce10c-337c-4162-99a7-ce3f49bd300e.png)

**Comment by joeyballentine** [comment]
Interesting. I wonder if it's not properly clearing out the vram after crashing when this happens. Con you tell by your vram in task manager or something that chaiNNer still has the vram allocated when this happens?

**Comment by dem10com** [comment]
If it was, shouldn't I get a good result for the 2048x2048 master file when I turn on the computer for the first time? 

When I check after getting the error, I get the result like this. 5 pyton 3.9 procces running in background. I just realized that even after exiting the program these continue to run in the background

![Screen Shot 2022-08-30 at 15 11 09](https://user-images.githubusercontent.com/111634201/187434977-26903233-b518-41a8-84c0-1befce5aa0b2.png)

using first time chainner.
![Screen Shot 2022-08-30 at 15 16 38](https://user-images.githubusercontent.com/111634201/187435380-1ec3dcce-1872-4ea3-8e3f-b745090218e7.png)

**Comment by dem10com** [comment]
i reset my computer. Run chainner. Look at my vram on statics. Almost empty

![Screen Shot 2022-08-30 at 15 35 28](https://user-images.githubusercontent.com/111634201/187438384-fe3b5b6c-a19a-49d2-bb8a-3389098d277d.png)

After i run and get error and quit application. memory never clear.

![Screen Shot 2022-08-30 at 15 36 36](https://user-images.githubusercontent.com/111634201/187438549-c00a0e45-7e7d-4edc-89dd-eecd0a9bd69e.png)

**Comment by dem10com** [comment]
After waiting for a while, the memory is still not reset, and when you close the Pyton 3.9 on my background proccess vram is resetting. 

![Screen Shot 2022-08-30 at 15 41 21](https://user-images.githubusercontent.com/111634201/187439602-239de808-0d6e-4336-b00a-b7268cbf6c65.png)

**Comment by dem10com** [comment]
I think the problem is that python 3.9 is constantly consuming memory in the background.

**Comment by joeyballentine** [comment]
Oh wow that's not good. chaiNNer is supposed to quit it's backend when it closes. Maybe there's something specific on Mac causing that to not work properly. Does that happen no matter what, or only if you get an ncnn error?

**Comment by joeyballentine** [comment]
Ok, yeah that might be an issue. Can you send your logs over?

**Comment by dem10com** [comment]
sure;

[main.log](https://github.com/joeyballentine/chaiNNer/files/9453683/main.log)
[renderer.log](https://github.com/joeyballentine/chaiNNer/files/9453684/renderer.log)

**Comment by joeyballentine** [comment]
Ok, this looks like one of three things:
- I either need to ignore vkQueueSubmit errors 
- I need to manually flush vram on vkQueueSubmit error
- I need to go back and update ncnn to not raise en exception on vkQueueSubmit error

I'll investigate a bit, but idk how much I can accomplish without being able to test it myself

**Comment by dem10com** [comment]
I'm here whenever you need it for the test. 

thank you Joey.

**Comment by dem10com** [comment]
@joeyballentine  i try but, i am not using ARM.  My macos system is intel based hardware. ( hackintosh )

demon@Emrahs-iMac ~ % /Users/demon/Library/Application\ Support/chaiNNer/python/python/bin/python3.9 -m pip install /Users/demon/Downloads/ncnn-vulkan-python-vkQueuefailure-test-1-macos/ncnn_vulkan-2022.8.30-cp39-cp39-macosx_11_0_arm64.whl
ERROR: ncnn_vulkan-2022.8.30-cp39-cp39-macosx_11_0_arm64.whl is not a supported wheel on this platform.
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the '/Users/demon/Library/Application Support/chaiNNer/python/python/bin/python3.9 -m pip install --upgrade pip' command.
demon@Emrahs-iMac ~ % /Users/demon/Library/Application\ Support/chaiNNer/python/python/bin/python3.9 -m pip install --upgrade pip
Requirement already satisfied: pip in ./Library/Application Support/chaiNNer/python/python/lib/python3.9/site-packages (21.2.4)
Collecting pip
  Downloading pip-22.2.2-py3-none-any.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 921 kB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-22.2.2
demon@Emrahs-iMac ~ % /Users/demon/Library/Application\ Support/chaiNNer/python/python/bin/python3.9 -m pip install /Users/demon/Downloads/ncnn-vulkan-python-vkQueuefailure-test-1-macos/ncnn_vulkan-2022.8.30-cp39-cp39-macosx_11_0_arm64.whl
ERROR: ncnn_vulkan-2022.8.30-cp39-cp39-macosx_11_0_arm64.whl is not a supported wheel on this platform.
demon@Emrahs-iMac ~ %

**Comment by joeyballentine** [comment]
Oh my bad. I will upload the correct one soon.

**Comment by joeyballentine** [comment]
[ncnn-vulkan-python-vkQueuefailure-test-1-macos_cp39-macosx_x86_64.zip](https://github.com/joeyballentine/chaiNNer/files/9461132/ncnn-vulkan-python-vkQueuefailure-test-1-macos_cp39-macosx_x86_64.zip)
@dem10com

**Comment by joeyballentine** [comment]
Are you quitting chaiNNer normally when this happens? It's supposed to kill the process on exit but if you're force closing chaiNNer it wouldn't be doing that necessarily. Idl what else it would be

**Comment by discordinated** [comment]
I have the same issue with Python3.9 being left running after exiting ChaiNNer on my M1 Max studio. I don't even need to run a chain, just open and closer ChaiNNer and the process will not close itself. 

I tried the 1st whl update you posted above - same issue.

**Comment by joeyballentine** [comment]
Ok. Maybe on Mac it just can't properly kill the process. I will try to fix that

**Comment by Jason-Bloomer** [comment]
I am encountering a very similar if not the same issue on Windows 10 as well. When using a file iterator I'll eventually run into an error which is exactly what dem10com posted screenshots of, I've posted my own as well. This only seems to happen when attempting to process images larger than 512x512. If I use a resize node to scale it down first this doesnt happen. However, I've looked and there are no extra background processes hanging about, and chaiNNer isn't eating up a bunch of resources.

An error occurred in a NCNN Upscale Image node:

An unexpected error occurred during NCNN processing.

Input values (partial):
• Image: RGB image 591x900
• Number of Tiles: Auto

![image](https://user-images.githubusercontent.com/86666099/188635489-809b1a24-1e8c-4087-9fb0-8e477e6cf396.png)

I can make a separate issue for this since it's a different OS if you'd like. But the error looks so similar, I figure it is likely related in some way.

**Comment by joeyballentine** [comment]
@dem10com has this issue been fixed?

**Comment by dem10com** [comment]
I checked and unfortunately it doesn't work. same black screen

![Screen Shot 2022-09-16 at 09 45 05](https://user-images.githubusercontent.com/111634201/190574046-dc3c6e72-df9d-4b38-a0a7-d439d7b462c6.png)

**Comment by dem10com** [comment]
here is my detail;
![Screen Shot 2022-09-16 at 09 46 40](https://user-images.githubusercontent.com/111634201/190574263-cd347ad6-3eec-4d09-ad6d-98161939c4bd.png)

**Comment by dem10com** [comment]
If it matters, I use realsr-ncnn-vulkan over the terminal and there is no problem.

![Screen Shot 2022-09-16 at 10 42 34](https://user-images.githubusercontent.com/111634201/190584436-31081e24-45f2-4066-820d-68fdd271dae7.png)

**Comment by dem10com** [comment]
i also try my mac book pro m1 ( monterey 12.5.1 ) it doesn't work either

<img width="1141" alt="Screen Shot 2022-09-16 at 11 41 41" src="https://user-images.githubusercontent.com/111634201/190596257-b60f5401-6d09-4364-a5ca-33b54f8b6f2e.png">

**Comment by joeyballentine** [comment]
@nihui would you happen to have a fix for this on macos as well?

**Comment by joeyballentine** [comment]
@dem10com could you set a manual tiling mode, like 64 tiles, and try again?

**Comment by dem10com** [comment]
i try joey, i try everything :) believe me nothing happened

**Comment by joeyballentine** [comment]
Unfortunately I don't think there's anything I can do about this. The fix for vkQueueSubmit problems on windows is changing a registry key yourself, and idk what you'd need to do if anything to fix it on Mac :(

**Comment by joeyballentine** [comment]
@dem10com would you mind testing the latest version (0.14) and seeing if this issue is fixed?

**Comment by dem10com** [comment]
@joeyballentine Works perfect! thank you Joey
